name: Release PDF

on:
  # Triggers the workflow on push to main, if any *.typ changed
  push:
    branches: ["main"]
    paths:
      - "**/*.typ"

  # Allows one to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Required for creating a release
    permissions:
      contents: write

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Compile manual
        uses: lvignoli/typst-action@main
        with:
          # Space separated list of paths to the .typ files
          source_file: manual.typ
          options: |
            --font-path
            .fonts

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "manual.pdf"

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/*.pdf"
          tag: ${{ steps.date.outputs.today }}
          name: "Release ${{ steps.date.outputs.today }}"
          body: "Automated release for ${{ steps.date.outputs.today }}"
          # Overwrite if multiple releases same day
          allowUpdates: true
